
version: '3.2'

services: 
    fish:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports: 
            - 8080:8080
        environment: 
            POSTGRES_URL: "postgres://postgres:password@postgres/fish"
            RUST_LOG: debug
    postgres:
        image: postgres
        restart: always
        environment: 
            POSTGRES_PASSWORD: password
            POSTGRES_DB: fish
            POSTGRES_USER: postgres
