
version: '3.9'

services: 
    fish:
        depends_on: 
            - postgres
        build:
            context: .
            dockerfile: ./Dockerfile
            args: 
                DATABASE_URL: "postgres://postgres:password@127.0.0.1/fish"
        network_mode: host
        environment: 
            DATABASE_URL: "postgres://postgres:password@127.0.0.1/fish"
            RUST_LOG: debug
    postgres:
        image: postgres
        network_mode: host
        restart: always
        environment: 
            POSTGRES_PASSWORD: password
            POSTGRES_DB: fish
            POSTGRES_USER: postgres
